# Render deployment configuration for CodeTantra Automation

services:
  # Backend API Service
  - type: web
    name: codetantra-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend && python init_database.py
    startCommand: cd backend && python main.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://admin:l9F1rk7UXCmY8UnOFcYeUiULbJ1kHeYO@dpg-d3fv09vdiees73bh8g2g-a.oregon-postgres.render.com/codetantradb
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_URL
        value: https://codetantra-frontend.onrender.com
      - key: ADMIN_EMAIL
        value: admin@codetantra.ac.in
      - key: ADMIN_PASSWORD
        value: admin123

  # Frontend Website Service
  - type: web
    name: codetantra-frontend
    env: static
    plan: free
    buildCommand: echo "Frontend build complete"
    staticPublishPath: backend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
